import BreadCrumb from "@/components/BreadCrumb"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const title = "Thông tin giới thiệu về công ty du lịch đà nẵng Dacotours";

export const metadata = {
  title,
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div className="w-full bg-white py-5">
      <div className="h-screen max-container">
        <BreadCrumb />
        <h1>About us</h1>
        <p>Our story</p>
        <Accordion type="single" collapsible className="w-full max-w-[500px]">
          <AccordionItem value="item-1" className="border border-slate-300 px-3 rounded-md">
            <AccordionTrigger className="hover:no-underline">Is it accessible?</AccordionTrigger>
            <AccordionContent>
              Yes. It adheres to the WAI-ARIA design pattern.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>Is it styled?</AccordionTrigger>
            <AccordionContent>
              Yes. It comes with default styles that matches the other
              components&apos; aesthetic.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>Is it animated?</AccordionTrigger>
            <AccordionContent>
              Yes. It&apos;s animated by default, but you can disable it if you
              prefer.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  )
}